# For development !
version: '3.9'
services:
  backend:
    build: 
      context: backend
      dockerfile: Dockerfile
    ports: 
      - "4000:4000"
    volumes:
      - ./backend/src:/app/src
      - ./backend/data:/app/data