# Build Stage
FROM node:18.3.0-bullseye as build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install --production

# Production Stage
FROM node:18.3.0-alpine3.15 as production-stage
WORKDIR /app
COPY --from=build-stage /app /app
COPY . .

## Launch the wait tool and then the application
CMD npm start